val book ="Marx e Engels partem de uma análise histórica, distinguindo as várias formas de opressão social durante os séculos e situam a burguesia moderna como nova classe opressora. Não deixam, porém, de citar seu grande papel revolucionário, tendo destruído o poder monárquico e religioso valorizando a liberdade econômica extremamente competitiva e um aspecto monetário frio em detrimento das relações pessoais e sociais, assim tratando o operário como uma simples peça de trabalho. Esse aspecto, juntamente com os recursos de aceleração de produção (tecnologia e divisão do trabalho), destrói todo atrativo para o trabalhador, deixando-o completamente desmotivado e contribuindo para a sua miserabilidade e coisificação. Além disso, analisam o desenvolvimento de novas necessidades tecnológicas na indústria e de novas necessidades de consumo impostas ao mercado consumidor.\n" +
        "\n" +
        "Afirmam sobre o proletariado: \"Sua luta contra a burguesia começa com sua própria existência\". O operariado, tomando consciência de sua situação, tende a se organizar e lutar contra a opressão, e ao tomar conhecimento do contexto social e histórico onde está inserido, especifica seu objetivo de luta. Sua organização é ainda maior pois toma um caráter transnacional, já que a subjugação ao capital despojou-o de qualquer nacionalismo. Outro ponto que legitima a justiça na vitória do proletariado seria de que este, após vencida a luta de classes, não poderia legitimar seu poder sob forma de opressão, pois defende exatamente o interesse da grande maioria: a abolição da propriedade (“Os proletários nada têm de seu para salvaguardar”).\n" +
        "\n" +
        "O Manifesto Comunista faz uma dura crítica ao modo de produção capitalista e à forma como a sociedade se estruturou através dele. Busca organizar o proletariado como classe social capaz de reverter sua precária situação e descreve os vários tipos de pensamento comunista, assim como define o objetivo e os princípios do socialismo científico.\n" +
        "\n" +
        "A exclusividade entre os proletários conscientes, portanto comunistas, segundo Marx e Engels, é de que visam a abolição da propriedade privada e lutam embasados num conhecimento histórico da organização social; são, portanto, revolucionários. Além disso, destaca que o comunismo não priva do poder de apropriação dos produtos sociais; apenas elimina o poder de subjugar o trabalho alheio por meio dessa apropriação. Com o desenvolvimento do socialismo a divisão em classes sociais desapareceria e o poder público perderia seu caráter opressor, enfim seria instaurada uma sociedade comunista.\n" +
        "\n" +
        "No terceiro capítulo, analisa e critica três tipos de socialismo. O socialismo reacionário, que seria uma forma de a elite conquistar a simpatia do povo e, mesmo tendo analisado as grandes contradições da sociedade, olhava-as do ponto de vista burguês e procurava manter as relações de produção e de troca; o socialismo conservador, com seu caráter reformador e anti-revolucionário; e o socialismo utópico, que apesar de fazer uma análise crítica da situação operária não se apoia em luta política, tornando a sociedade comunista inatingível.\n" +
        "\n" +
        "Por fim, no quarto capítulo fecha com as principais ideias do Manifesto, com destaque na questão da propriedade privada e motivando a união entre os operários. Acentua a união transnacional, em detrimento do nacionalismo esbanjado pelas nações, como manifestado na célebre frase: Proletários de todos os países, uni-vos![1]\n" +
        "\n" +
        "Marx e Engels partem de uma análise histórica, distinguindo as várias formas de opressão social durante os séculos e situam a burguesia moderna como nova classe opressora. Não deixam, porém, de citar seu grande papel revolucionário, tendo destruído o poder monárquico e religioso valorizando a liberdade econômica extremamente competitiva e um aspecto monetário frio em detrimento das relações pessoais e sociais, assim tratando o operário como uma simples peça de trabalho. Esse aspecto, juntamente com os recursos de aceleração de produção (tecnologia e divisão do trabalho), destrói todo atrativo para o trabalhador, deixando-o completamente desmotivado e contribuindo para a sua miserabilidade e coisificação. Além disso, analisam o desenvolvimento de novas necessidades tecnológicas na indústria e de novas necessidades de consumo impostas ao mercado consumidor.\n" +
        "\n" +
        "Afirmam sobre o proletariado: \"Sua luta contra a burguesia começa com sua própria existência\". O operariado, tomando consciência de sua situação, tende a se organizar e lutar contra a opressão, e ao tomar conhecimento do contexto social e histórico onde está inserido, especifica seu objetivo de luta. Sua organização é ainda maior pois toma um caráter transnacional, já que a subjugação ao capital despojou-o de qualquer nacionalismo. Outro ponto que legitima a justiça na vitória do proletariado seria de que este, após vencida a luta de classes, não poderia legitimar seu poder sob forma de opressão, pois defende exatamente o interesse da grande maioria: a abolição da propriedade (“Os proletários nada têm de seu para salvaguardar”).\n" +
        "\n" +
        "O Manifesto Comunista faz uma dura crítica ao modo de produção capitalista e à forma como a sociedade se estruturou através dele. Busca organizar o proletariado como classe social capaz de reverter sua precária situação e descreve os vários tipos de pensamento comunista, assim como define o objetivo e os princípios do socialismo científico.\n" +
        "\n" +
        "A exclusividade entre os proletários conscientes, portanto comunistas, segundo Marx e Engels, é de que visam a abolição da propriedade privada e lutam embasados num conhecimento histórico da organização social; são, portanto, revolucionários. Além disso, destaca que o comunismo não priva do poder de apropriação dos produtos sociais; apenas elimina o poder de subjugar o trabalho alheio por meio dessa apropriação. Com o desenvolvimento do socialismo a divisão em classes sociais desapareceria e o poder público perderia seu caráter opressor, enfim seria instaurada uma sociedade comunista.\n" +
        "\n" +
        "No terceiro capítulo, analisa e critica três tipos de socialismo. O socialismo reacionário, que seria uma forma de a elite conquistar a simpatia do povo e, mesmo tendo analisado as grandes contradições da sociedade, olhava-as do ponto de vista burguês e procurava manter as relações de produção e de troca; o socialismo conservador, com seu caráter reformador e anti-revolucionário; e o socialismo utópico, que apesar de fazer uma análise crítica da situação operária não se apoia em luta política, tornando a sociedade comunista inatingível.\n" +
        "\n" +
        "Por fim, no quarto capítulo fecha com as principais ideias do Manifesto, com destaque na questão da propriedade privada e motivando a união entre os operários. Acentua a união transnacional, em detrimento do nacionalismo esbanjado pelas nações, como manifestado na célebre frase: Proletários de todos os países, uni-vos![1]\n" +
        "\n"
